# Generated by Django 3.1 on 2021-11-16 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id_alumnos', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('jornada', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('grado', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='clases',
            fields=[
                ('id_clases', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='materias',
            fields=[
                ('id_materias', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id_profesores', models.AutoField(primary_key=True, serialize=False)),
                ('carnet', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('dpi', models.CharField(max_length=20)),
                ('jornada', models.CharField(max_length=10)),
                ('especialidad', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='secciones',
            fields=[
                ('id_secciones', models.AutoField(primary_key=True, serialize=False)),
                ('salon', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='horarios',
            fields=[
                ('id_horarios', models.AutoField(primary_key=True, serialize=False)),
                ('horario_curso', models.CharField(max_length=30)),
                ('fk_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.clases')),
                ('fk_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.secciones')),
            ],
        ),
        migrations.AddField(
            model_name='clases',
            name='fk_materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.materias'),
        ),
        migrations.AddField(
            model_name='clases',
            name='fk_profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.profesores'),
        ),
        migrations.CreateModel(
            name='asistencias',
            fields=[
                ('id_asistencias', models.AutoField(primary_key=True, serialize=False)),
                ('asistio', models.CharField(max_length=30)),
                ('fecha', models.DateField()),
                ('fk_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.alumnos')),
                ('fk_clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.clases')),
            ],
        ),
        migrations.AddField(
            model_name='alumnos',
            name='fk_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edu.secciones'),
        ),
    ]
